use std::hash::{BuildHasher, Hash, Hasher};
use rapidhash::fast::SeedableState;
use rustc_hash::FxHasher;
use crate::util::bitfield::BitField;

/// Some tests were done to find a decent trade-off between bit count performance and false-positive
/// rate. Effectively, with 140 items in the bloom filter (and 230 not-present test samples) and
/// 1024 bits and 3 hashes in the bloom filter
///  - Average of 206.72ns per 10-character query
///  - ~5% false positive rate
/// Leading me to believe that for datasets ~100-200 items, 1024 bits and 3 hashes should suffice.
pub(crate) struct BloomFilter<'a> {
    bits: BitField,
    hash_count: usize,
    rapid_hash: SeedableState<'a>,
}

impl<'a> BloomFilter<'a> {
    fn get_n_hashes(&self, string: &str) -> Vec<usize> {
        let mut fx_hasher = FxHasher::default();
        string.hash(&mut fx_hasher);
        let hash_1 = self.rapid_hash.hash_one(string) as usize;
        let hash_2 = fx_hasher.finish() as usize;
        let mut hashes = Vec::from([
            hash_1 % self.bits.bit_count(),
            hash_2 % self.bits.bit_count(),
        ]);
        for i in 2..self.hash_count {
            hashes.push(hash_1.wrapping_add(hash_2.overflowing_mul(i).0) % self.bits.bit_count());
        }
        hashes
    }

    /// Creates a new bloom filter with a specified bit count and hash function count.
    /// Bit count is rounded up to the nearest 8, and hash count can be anything greater than 1.
    pub fn init(bit_count: usize, hash_count: usize) -> Self {
        assert!(hash_count > 1);
        let rapid_hash = SeedableState::fixed();
        BloomFilter {
            bits: BitField::new(bit_count),
            hash_count,
            rapid_hash,
        }
    }

    /// Adds a new value to the bloom filter
    pub fn add(&mut self, string: &str) {
        for bit in self.get_n_hashes(string) {
            self.bits.up(bit);
        }
    }

    /// Returns true if the value might be in the bloom filter, and false if it's definitely not
    pub fn maybe_in_filter(&self, string: &str) -> bool {
        for bit in self.get_n_hashes(string) {
            if !self.bits.get(bit) {
                return false
            }
        }
        true
    }
}

#[cfg(test)]
mod tests {
    use toml::to_string;
    use crate::util::bloomfilter::BloomFilter;

    fn get_good_string() -> Vec<String> {
        Vec::from([
                  "e4y8nUARCF".to_string(),
                  "nvVTNlurYj".to_string(),
                  "kY3BxjU413".to_string(),
                  "MXT74zb6l6".to_string(),
                  "J59i9aTRtu".to_string(),
                  "1zPzVKq3KK".to_string(),
                  "s4TlbFukUu".to_string(),
                  "sU895CVcJc".to_string(),
                  "VcWoae5tK9".to_string(),
                  "eqbwQKIZII".to_string(),
                  "bgOBLBKfaZ".to_string(),
                  "c4h1kOeLeq".to_string(),
                  "Sp8DJnQnZ2".to_string(),
                  "FEVbv5UZgV".to_string(),
                  "o9iQMoFk3y".to_string(),
                  "MtwFs1ZKZe".to_string(),
                  "NYOyAar0K5".to_string(),
                  "dhC7qGWuzc".to_string(),
                  "ExpjGDfT5K".to_string(),
                  "io4HdgyEpQ".to_string(),
                  "nTk7s8AYnL".to_string(),
                  "UWwDbcB2sd".to_string(),
                  "u2k39uy9it".to_string(),
                  "cYC61Eh3e8".to_string(),
                  "m1o6QR3UpV".to_string(),
                  "xgyRgUdqI4".to_string(),
                  "Ie6As57BGE".to_string(),
                  "FiSqwbt0Na".to_string(),
                  "OXQ5IPCnD0".to_string(),
                  "sZCGdfagLV".to_string(),
                  "3uydhhKWX9".to_string(),
                  "HB6J0oHP76".to_string(),
                  "muCtwIXdMb".to_string(),
                  "L36XvCNNFI".to_string(),
                  "UqG3tI0JHv".to_string(),
                  "3CkKJeHpCN".to_string(),
                  "KQlCijG1la".to_string(),
                  "f9hTdOKkq0".to_string(),
                  "xPJURhsP0P".to_string(),
                  "pxVibkmpzD".to_string(),
                  "CRlDVz1y0M".to_string(),
                  "h4vqG3VfzH".to_string(),
                  "QKOjHwIrWj".to_string(),
                  "r1is8LoiYV".to_string(),
                  "qkkbdpMhMK".to_string(),
                  "uicjXgPsOi".to_string(),
                  "EKJuRK940u".to_string(),
                  "sivkjzeomD".to_string(),
                  "S7J3rLo7xJ".to_string(),
                  "s0fOpFzxSv".to_string(),
                  "QAQqRBPkQc".to_string(),
                  "HPkdzWR7ZA".to_string(),
                  "sCyTTG6kvs".to_string(),
                  "Puu1Abm8QL".to_string(),
                  "THDyixUNFj".to_string(),
                  "Pb4Hsvxf52".to_string(),
                  "enAnQr0JrU".to_string(),
                  "O96NL6hnLB".to_string(),
                  "53OTuGzLAD".to_string(),
                  "KyuplWgkHK".to_string(),
                  "o5NfPOnRve".to_string(),
                  "cgTZ92cnSA".to_string(),
                  "grTJu6kTO4".to_string(),
                  "NxdjwOAm5t".to_string(),
                  "RT2Q9L6w8U".to_string(),
                  "SHPFqECath".to_string(),
                  "NfijHex3Y0".to_string(),
                  "9KXCWojLSc".to_string(),
                  "FlZxs2WMUP".to_string(),
                  "pXfJeXePWs".to_string(),
                  "PCJbVBLFCV".to_string(),
                  "6NH8rVp89c".to_string(),
                  "eYkvG9WIK2".to_string(),
                  "3Jjbl8FUNI".to_string(),
                  "PJNuXXqerM".to_string(),
                  "TzOxEbQlG0".to_string(),
                  "shDanEHwuN".to_string(),
                  "QQsI24N2HU".to_string(),
                  "riyKu5HzMo".to_string(),
                  "CusPq22eM1".to_string(),
                  "j7H5XU2v8b".to_string(),
                  "CrmBSGdw9S".to_string(),
                  "rfj2i64irY".to_string(),
                  "synSIh5eXG".to_string(),
                  "aiJ0irArwH".to_string(),
                  "1eojjSVote".to_string(),
                  "jY0pSr3YKC".to_string(),
                  "RSueC0Ncd8".to_string(),
                  "bFDxa7A2PN".to_string(),
                  "mfOM3n2e7E".to_string(),
                  "4vIzdZqX7P".to_string(),
                  "2Dha7K54kp".to_string(),
                  "bwlILceniC".to_string(),
                  "zRZQWd9Gw1".to_string(),
                  "mO2rk2XuXk".to_string(),
                  "2DbGnr4Kjr".to_string(),
                  "EuG8z1ieW2".to_string(),
                  "dlNQl1KrEF".to_string(),
                  "EZZrhH4YNu".to_string(),
                  "i7siHIgEzL".to_string(),
                  "2hWYOTXS8J".to_string(),
                  "zvS3pup8VL".to_string(),
                  "jmNGkyMMPQ".to_string(),
                  "O3ru2StivT".to_string(),
                  "BVGvFjF2Zb".to_string(),
                  "Z4EI1c8pVP".to_string(),
                  "RI4DVroxwm".to_string(),
                  "TBRbXQm08L".to_string(),
                  "WAGZHk4Ba9".to_string(),
                  "CGEiXcN062".to_string(),
                  "1qd3uByLCl".to_string(),
                  "pbdljFy3oi".to_string(),
                  "419l3MRkeg".to_string(),
                  "RNNt59YpDB".to_string(),
                  "qb0SFRMqse".to_string(),
                  "8EzjqIvEBq".to_string(),
                  "eHUKkh797m".to_string(),
                  "v1cghUcc0z".to_string(),
                  "f4Smdvi6yv".to_string(),
                  "0SIUPHxrSp".to_string(),
                  "pe4lGJEQmD".to_string(),
                  "i6YOqaMwm1".to_string(),
                  "2wXBtKnrgX".to_string(),
                  "u956mNMzws".to_string(),
                  "6jFfPpJaK8".to_string(),
                  "kBKbgsFoUC".to_string(),
                  "QVi7snyn50".to_string(),
                  "Y2unKRiLuH".to_string(),
                  "TI7gXqQPRg".to_string(),
                  "s3g5U8a1Ic".to_string(),
                  "aAngSzlD03".to_string(),
                  "axZADF23he".to_string(),
                  "JAzAuJ7aJy".to_string(),
                  "6RygEMMcnU".to_string(),
                  "1aH9LiNU9t".to_string(),
                  "u8VD3CKQCY".to_string(),
                  "tddZfFJQpy".to_string(),
                  "cQrUempfhR".to_string(),
                  "CSQBsiOxMZ".to_string(),
                  "3dSlm7nv59".to_string(),
        ])
    }

    fn get_bad_string() -> Vec<String> {
        Vec::from([
            "W2BfwqdcWz".to_string(),
            "3H4DtSZkDI".to_string(),
            "Mnz7tKATn2".to_string(),
            "Fvic9ZUtS4".to_string(),
            "yJGFH1Cy6A".to_string(),
            "wXNKhYLLgx".to_string(),
            "KJwU2ewLDs".to_string(),
            "FEdOEDafVQ".to_string(),
            "l4vXbK8w7W".to_string(),
            "w3jdyIjF9t".to_string(),
            "hJXLwu1jT5".to_string(),
            "PVsrkdSjnv".to_string(),
            "aeMiCfXgkx".to_string(),
            "YniOGBNlmd".to_string(),
            "C0K1GCNVzW".to_string(),
            "DMWoXfJGZ2".to_string(),
            "HreRrGITTT".to_string(),
            "F1akMguJZG".to_string(),
            "dBSHHsLLoq".to_string(),
            "v4kFf9XwBS".to_string(),
            "5jAcE2afmM".to_string(),
            "s0ucF2nuFg".to_string(),
            "vNzdIaYJRJ".to_string(),
            "S7g6TBVg4P".to_string(),
            "uG2w95T3aQ".to_string(),
            "AznM5KJ84t".to_string(),
            "I9VJ057Vau".to_string(),
            "lhvEYKoeEy".to_string(),
            "bs4wNBR03m".to_string(),
            "vwc8XDKApH".to_string(),
            "DaxuFGfHfn".to_string(),
            "QPYwWuq45a".to_string(),
            "Co4vPdyh9T".to_string(),
            "EsnFnZuUQh".to_string(),
            "A3CYyCUbok".to_string(),
            "UxQS9vJECI".to_string(),
            "85KmexhbhI".to_string(),
            "v1qOP9u3ck".to_string(),
            "Cl4VZneyOQ".to_string(),
            "2Jnf7BTElK".to_string(),
            "6lExzwzut7".to_string(),
            "S4Aig5BBXj".to_string(),
            "a96QDhKdna".to_string(),
            "ULHzymV9gi".to_string(),
            "QqsTV0LvGD".to_string(),
            "apjLIiazZh".to_string(),
            "NtkqjrhmzG".to_string(),
            "33j89pyXrU".to_string(),
            "nKl6zUPgEB".to_string(),
            "ybx71SMrQ5".to_string(),
            "bkFZrKXy5n".to_string(),
            "YqLqmuOkja".to_string(),
            "QMqg7GDOGI".to_string(),
            "PguFWWCBzc".to_string(),
            "ZfjjkOTZ8o".to_string(),
            "i1QFbrdIrP".to_string(),
            "oBgxlh5bzd".to_string(),
            "j62uQCDgs6".to_string(),
            "ezuNVVc3yZ".to_string(),
            "wwRJrHom75".to_string(),
            "e6Mzkn5OEF".to_string(),
            "wqD2GF06DI".to_string(),
            "U7nU1rdvZZ".to_string(),
            "xb9s4C0I1V".to_string(),
            "R9HztJiSHZ".to_string(),
            "JOF7EDP8dg".to_string(),
            "8tyhXrdYeU".to_string(),
            "I8xcmV3gWN".to_string(),
            "o5x3ldU9CM".to_string(),
            "wQmVysGguc".to_string(),
            "ZEvgUr2dbD".to_string(),
            "aYYZS7pzQl".to_string(),
            "PZo1IFh5q7".to_string(),
            "A6NPF0r0Wx".to_string(),
            "sF6zDwE3wE".to_string(),
            "JoynmUu74L".to_string(),
            "M47wxclFGF".to_string(),
            "pgRsEMhPwF".to_string(),
            "6VED9YlfTs".to_string(),
            "6gbvWTIpOV".to_string(),
            "YYq6IWayX8".to_string(),
            "jm05nnYmDE".to_string(),
            "0pvpAPmV7h".to_string(),
            "4YXpc45CZi".to_string(),
            "Nfx1Pgoc5L".to_string(),
            "yAjYREfPVb".to_string(),
            "4JzAWxeg6U".to_string(),
            "uETElSm0sW".to_string(),
            "DYNigtZCYM".to_string(),
            "FgJj9GlZwH".to_string(),
            "eGqm5ZpchD".to_string(),
            "dW112ZxSiz".to_string(),
            "ju0PT4Z7q2".to_string(),
            "K6za1ucmRD".to_string(),
            "Wt50xgymW6".to_string(),
            "38mAeCOeSX".to_string(),
            "AV0pAYYZcn".to_string(),
            "OIL98ihWwV".to_string(),
            "IU09iCot85".to_string(),
            "1bSf9UT6x4".to_string(),
            "meN6NMGpyC".to_string(),
            "aOn6GUnkY8".to_string(),
            "Igel8gbbki".to_string(),
            "AWy2JClKvV".to_string(),
            "j7fZzXyveY".to_string(),
            "u82UndTc0b".to_string(),
            "VaWGty4KW2".to_string(),
            "1V6S0hg5db".to_string(),
            "ndXq648umw".to_string(),
            "M1nXJAPorY".to_string(),
            "N9cdQF5Yej".to_string(),
            "K6vjxMJesi".to_string(),
            "dQHEdtdj2d".to_string(),
            "vw2jd2qmkM".to_string(),
            "3HBcqUlKxf".to_string(),
            "qxPkJrOzLt".to_string(),
            "P1mzOf9V8E".to_string(),
            "SERuSfRMI9".to_string(),
            "Gc0ajw22IT".to_string(),
            "P4wPCpZbhu".to_string(),
            "4DHg9ygbUM".to_string(),
            "QrBZYlbVi1".to_string(),
            "i4W5rNprAn".to_string(),
            "0YJZqTiQhX".to_string(),
            "9bAPis0O3k".to_string(),
            "6heK2kbEB6".to_string(),
            "cyGvTanUcL".to_string(),
            "ezvztH1lnC".to_string(),
            "gfnsE9hQYi".to_string(),
            "qAHm0QmMxk".to_string(),
            "Q2JUqXhknW".to_string(),
            "9kj8DSmUIx".to_string(),
            "GlPpVpNHe1".to_string(),
            "3Jgbd6VvNg".to_string(),
            "FyTw9Qdrsb".to_string(),
            "BXeJhBVqiA".to_string(),
            "58Uyu8rRZH".to_string(),
            "NXkIfTYR5P".to_string(),
            "8vmZcYAc8N".to_string(),
            "Qs2QGXJq0U".to_string(),
            "rcIA8USkUN".to_string(),
            "vLgZrPka3C".to_string(),
            "uPBavlVEMV".to_string(),
            "QmTvkDBjXa".to_string(),
            "DMaoEamkCo".to_string(),
            "YlT5H2MPlZ".to_string(),
            "0qqSdOzg9t".to_string(),
            "Pd83jgg0aY".to_string(),
            "rWPwF915WC".to_string(),
            "654jVw6HOp".to_string(),
            "Dum6INbcxg".to_string(),
            "AEjAxc34Yb".to_string(),
            "ZxsMojQzCS".to_string(),
            "UQzPbb5gnz".to_string(),
            "0AiFa4HYFH".to_string(),
            "P6NhDdLzM0".to_string(),
            "B5gwzPFzCo".to_string(),
            "Xv6YZzBbp1".to_string(),
            "vFKEngQLQS".to_string(),
            "HixZZQPvlg".to_string(),
            "xWT1xCCcj2".to_string(),
            "D7S6hgw2ul".to_string(),
            "7hpF9orwnD".to_string(),
            "vQCFs1G6Sn".to_string(),
            "2v0eap9GNE".to_string(),
            "RoO0R9j3Fk".to_string(),
            "hs2xNkZVcQ".to_string(),
            "apnVbwCftM".to_string(),
            "DO10a7gvnA".to_string(),
            "rrErA9ORbF".to_string(),
            "YNwiCmqzXX".to_string(),
            "YvzoFtaDDP".to_string(),
            "nLDV0nJjlV".to_string(),
            "3HRKJZDmV8".to_string(),
            "jHfpn5pFz3".to_string(),
            "fkpDuyH5le".to_string(),
            "5PsgO0pm1P".to_string(),
            "f7NcwGdLsb".to_string(),
            "Bvd7HJwZVd".to_string(),
            "Qk9HffYOHb".to_string(),
            "RD5QwQYUDF".to_string(),
            "U3QpWKUFJT".to_string(),
            "hWHdIZyUyi".to_string(),
            "kgYHhkK4qj".to_string(),
            "lZo40l1djw".to_string(),
            "T1eBL1wjNr".to_string(),
            "YcuCOCZqWC".to_string(),
            "X1ga81aQjY".to_string(),
            "6CNLxyeKQJ".to_string(),
            "C8sLmJqeTa".to_string(),
            "AyYFgmKRkV".to_string(),
            "87c6IX6t0H".to_string(),
            "0ocg27pbxz".to_string(),
            "H96CEWWbzA".to_string(),
            "5isbQEGD1V".to_string(),
            "IFXzMvQaNQ".to_string(),
            "Dea9PMB9Jc".to_string(),
            "XN0GZiHbPy".to_string(),
            "4lxnaROJSf".to_string(),
            "UL6NeJNLFO".to_string(),
            "y3SNf2L6WI".to_string(),
            "gCPbbosdGf".to_string(),
            "gFGZzhmIYU".to_string(),
            "C0T5KJrmuR".to_string(),
            "bKGX5Xtxfm".to_string(),
            "BTjffNLXiW".to_string(),
            "AWMAfpsxvr".to_string(),
            "IsAnCqeoTW".to_string(),
            "kCswHVlvws".to_string(),
            "Ad61ROhCL8".to_string(),
            "iPwfPqaPa0".to_string(),
            "EKpDqi0eP9".to_string(),
            "acwLx7FPWd".to_string(),
            "YK45U8j3vu".to_string(),
            "z3j2TCg9Bx".to_string(),
            "svGk3tXRck".to_string(),
            "9ru2qT0bLX".to_string(),
            "HmLfYPIUBG".to_string(),
            "a4Z8RRT6dy".to_string(),
            "nvp6udMv3d".to_string(),
            "3cdSeW2V2y".to_string(),
            "ilXdpPzgXu".to_string(),
            "83YKub74HF".to_string(),
            "EvvLiV3kYr".to_string(),
            "OXtnYU5Moh".to_string(),
            "rY9mARHfCG".to_string(),
            "qYnD8gpgTR".to_string(),
            "DtExvKOzdD".to_string(),
            "alSNEFtWaX".to_string(),
            "5kDWYzMSPv".to_string(),
        ])
    }

    #[test]
    fn test_present_in_filter() {
        let mut filter = BloomFilter::init(128, 3);
        for s in get_good_string() {
            filter.add(s.as_str());
        }
        for s in get_good_string() {
            assert!(filter.maybe_in_filter(s.as_str()));
        }
        // Some may hash collide but at least 1 has to be not in the filter
        let mut filtered_count = 0;
        for s in get_bad_string() {
            if ! filter.maybe_in_filter(s.as_str()) {
                filtered_count += 1;
            }
        }
        println!("Filtered out: {}/{} ({:.2}%)", filtered_count, get_bad_string().len(), filtered_count as f32 / get_bad_string().len() as f32 * 100.0);
        assert!(filtered_count > 0);
    }
}
